name: Go Tripod WWW
markdown: redcarpet
highlighter: pigments
permalink: :title
gems:
  - jekyll-redirect-from
collections:
  case_studies:
    layout: master
    output: true
    permalink: /case-studies/:path/
