name: Go Tripod WWW
highlighter: rouge
permalink: :title
gems:
  - jekyll-redirect-from
collections:
  case_studies:
    layout: master
    output: true
    permalink: /case-studies/:path/
sass:
    sass_dir: assets/_sass
    style: :compressed
